export enum EventKind {
  WEDDING = "WEDDING",
  BAPTISM = "BAPTISM",
  BIRTHDAY_18 = "BIRTHDAY_18",
  BIRTHDAY_30 = "BIRTHDAY_30",
  BIRTHDAY_50 = "BIRTHDAY_50",
  BABY_SHOWER = "BABY_SHOWER",
  HOLY_COMMUNION = "HOLY_COMMUNION",
  OTHER = "OTHER",
}
