/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0
 */
export interface RegisterDto {
  email: string;
  /** Min. 8 characters,must contain at least one lowercase and one uppercase letter, digit and special character */
  password: string;
  name?: string;
}

export interface LoginDto {
  email: string;
  password: string;
}

export interface ResetPasswordDto {
  token: string;
  newPassword: string;
}

export type AuthControllerVerifyEmailParams = {
token: string;
};

export type AuthControllerRequestPasswordResetParams = {
email: string;
};

