/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0
 */
export interface RegisterDto {
  email: string;
  /** Min. 8 characters,must contain at least one lowercase and one uppercase letter, digit and special character */
  password: string;
  name?: string;
}

export interface LoginDto {
  email: string;
  password: string;
}

export interface ResetPasswordDto {
  token: string;
  newPassword: string;
}

export type CreateEventDtoKind = typeof CreateEventDtoKind[keyof typeof CreateEventDtoKind];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateEventDtoKind = {
  WEDDING: 'WEDDING',
  BAPTISM: 'BAPTISM',
  BIRTHDAY_18: 'BIRTHDAY_18',
  BIRTHDAY_30: 'BIRTHDAY_30',
  BIRTHDAY_50: 'BIRTHDAY_50',
  BABY_SHOWER: 'BABY_SHOWER',
  HOLY_COMMUNION: 'HOLY_COMMUNION',
  OTHER: 'OTHER',
} as const;

export interface CreateEventDto {
  title: string;
  description?: string;
  /** ISO 8601 */
  date?: string;
  location?: string;
  kind?: CreateEventDtoKind;
  templateKey?: string;
}

export type UpdateEventDtoKind = typeof UpdateEventDtoKind[keyof typeof UpdateEventDtoKind];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateEventDtoKind = {
  WEDDING: 'WEDDING',
  BAPTISM: 'BAPTISM',
  BIRTHDAY_18: 'BIRTHDAY_18',
  BIRTHDAY_30: 'BIRTHDAY_30',
  BIRTHDAY_50: 'BIRTHDAY_50',
  BABY_SHOWER: 'BABY_SHOWER',
  HOLY_COMMUNION: 'HOLY_COMMUNION',
  OTHER: 'OTHER',
} as const;

export interface UpdateEventDto {
  title: string;
  description?: string;
  /** ISO 8601 */
  date?: string;
  location?: string;
  kind?: UpdateEventDtoKind;
  templateKey?: string;
}

export interface CreateProgramItemDto {
  /** Indeks dnia (0 = główny dzień) */
  dayIndex: number;
  /** Godzina w formacie HH:mm */
  time: string;
  /** Nazwa ikony z lucide-react */
  icon?: string;
  header: string;
  subheader?: string;
  /** Pozycja w obrębie dnia/godziny */
  position?: number;
}

export interface UpdateProgramItemDto {
  /** Indeks dnia (0 = główny dzień) */
  dayIndex?: number;
  /** Godzina w formacie HH:mm */
  time?: string;
  /** Nazwa ikony z lucide-react */
  icon?: string;
  header?: string;
  subheader?: string;
  /** Pozycja w obrębie dnia/godziny */
  position?: number;
}

export interface CreateForInviteeDto {
  /** Bazowy URL frontendu do zbudowania publicznego linku */
  frontendBase?: string;
}

export interface InvitationsStatsDto {
  total: number;
  accepted: number;
  declined: number;
  tentative: number;
  viewed: number;
}

export type PublicEventDtoDate = { [key: string]: unknown };

export type PublicEventDtoLocation = { [key: string]: unknown };

export type PublicEventDtoDescription = { [key: string]: unknown };

/**
 * Konfiguracja/metadata szablonu (jeśli przypisany)
 */
export type PublicEventDtoTemplate = { [key: string]: unknown };

export interface PublicEventDto {
  title: string;
  date?: PublicEventDtoDate;
  location?: PublicEventDtoLocation;
  description?: PublicEventDtoDescription;
  /** Konfiguracja/metadata szablonu (jeśli przypisany) */
  template?: PublicEventDtoTemplate;
}

export interface PublicInviteeDto {
  fullName: string;
  seats: number;
}

/**
 * Aktualny status RSVP
 */
export type PublicInvitationGetResponseDtoStatus = typeof PublicInvitationGetResponseDtoStatus[keyof typeof PublicInvitationGetResponseDtoStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PublicInvitationGetResponseDtoStatus = {
  ACCEPTED: 'ACCEPTED',
  DECLINED: 'DECLINED',
  TENTATIVE: 'TENTATIVE',
  PENDING: 'PENDING',
} as const;

export interface PublicInvitationGetResponseDto {
  event: PublicEventDto;
  invitee: PublicInviteeDto;
  /** Aktualny status RSVP */
  status: PublicInvitationGetResponseDtoStatus;
}

export type PublicRsvpDtoStatus = typeof PublicRsvpDtoStatus[keyof typeof PublicRsvpDtoStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PublicRsvpDtoStatus = {
  ACCEPTED: 'ACCEPTED',
  DECLINED: 'DECLINED',
  TENTATIVE: 'TENTATIVE',
  PENDING: 'PENDING',
} as const;

export interface PublicRsvpDto {
  status: PublicRsvpDtoStatus;
  /** Ile osób przyjdzie (≤ seats) */
  count?: number;
  note?: string;
}

export type PublicRsvpResponseDtoStatus = typeof PublicRsvpResponseDtoStatus[keyof typeof PublicRsvpResponseDtoStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PublicRsvpResponseDtoStatus = {
  ACCEPTED: 'ACCEPTED',
  DECLINED: 'DECLINED',
  TENTATIVE: 'TENTATIVE',
  PENDING: 'PENDING',
} as const;

export type PublicRsvpResponseDtoRsvpAt = { [key: string]: unknown };

export type PublicRsvpResponseDtoRsvpCount = { [key: string]: unknown };

export interface PublicRsvpResponseDto {
  status: PublicRsvpResponseDtoStatus;
  rsvpAt?: PublicRsvpResponseDtoRsvpAt;
  rsvpCount?: PublicRsvpResponseDtoRsvpCount;
}

export interface CreateInviteeDto {
  fullName: string;
  email?: string;
  phone?: string;
  /**
   * Liczba miejsc dla zaproszonego
   * @minimum 1
   */
  seats?: number;
  groupName?: string;
  notes?: string;
}

export interface BulkCreateInviteesDto {
  items: CreateInviteeDto[];
}

export type AuthControllerVerifyEmailParams = {
token: string;
};

export type AuthControllerRequestPasswordResetParams = {
email: string;
};

export type ProgramControllerList200Item = { [key: string]: unknown };

export type ProgramControllerBulkBody = {
  items?: CreateProgramItemDto[];
};

export type ProgramControllerReorderBodyOrderItem = {
  id?: string;
  position?: number;
};

export type ProgramControllerReorderBody = {
  order?: ProgramControllerReorderBodyOrderItem[];
};

