/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0
 */
import type {
  AuthControllerRequestPasswordResetParams,
  AuthControllerVerifyEmailParams,
  LoginDto,
  RegisterDto,
  ResetPasswordDto
} from './api.gen.schemas';

import { orvalFetcher } from '../lib/orval-fetcher';


export type authControllerRegisterResponse201 = {
  data: void
  status: 201
}
    
export type authControllerRegisterResponseSuccess = (authControllerRegisterResponse201) & {
  headers: Headers;
};
;

export type authControllerRegisterResponse = (authControllerRegisterResponseSuccess)

export const getAuthControllerRegisterUrl = () => {


  

  return `/auth/register`
}

export const authControllerRegister = async (registerDto: RegisterDto, options?: RequestInit): Promise<authControllerRegisterResponse> => {
  
  return orvalFetcher<authControllerRegisterResponse>(getAuthControllerRegisterUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      registerDto,)
  }
);}


export type authControllerLoginResponse201 = {
  data: void
  status: 201
}
    
export type authControllerLoginResponseSuccess = (authControllerLoginResponse201) & {
  headers: Headers;
};
;

export type authControllerLoginResponse = (authControllerLoginResponseSuccess)

export const getAuthControllerLoginUrl = () => {


  

  return `/auth/login`
}

export const authControllerLogin = async (loginDto: LoginDto, options?: RequestInit): Promise<authControllerLoginResponse> => {
  
  return orvalFetcher<authControllerLoginResponse>(getAuthControllerLoginUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      loginDto,)
  }
);}


export type authControllerVerifyEmailResponse201 = {
  data: void
  status: 201
}
    
export type authControllerVerifyEmailResponseSuccess = (authControllerVerifyEmailResponse201) & {
  headers: Headers;
};
;

export type authControllerVerifyEmailResponse = (authControllerVerifyEmailResponseSuccess)

export const getAuthControllerVerifyEmailUrl = (params: AuthControllerVerifyEmailParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/auth/verify-email?${stringifiedParams}` : `/auth/verify-email`
}

export const authControllerVerifyEmail = async (params: AuthControllerVerifyEmailParams, options?: RequestInit): Promise<authControllerVerifyEmailResponse> => {
  
  return orvalFetcher<authControllerVerifyEmailResponse>(getAuthControllerVerifyEmailUrl(params),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}


export type authControllerRefreshResponse201 = {
  data: void
  status: 201
}
    
export type authControllerRefreshResponseSuccess = (authControllerRefreshResponse201) & {
  headers: Headers;
};
;

export type authControllerRefreshResponse = (authControllerRefreshResponseSuccess)

export const getAuthControllerRefreshUrl = () => {


  

  return `/auth/refresh`
}

export const authControllerRefresh = async ( options?: RequestInit): Promise<authControllerRefreshResponse> => {
  
  return orvalFetcher<authControllerRefreshResponse>(getAuthControllerRefreshUrl(),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}


export type authControllerLogoutResponse201 = {
  data: void
  status: 201
}
    
export type authControllerLogoutResponseSuccess = (authControllerLogoutResponse201) & {
  headers: Headers;
};
;

export type authControllerLogoutResponse = (authControllerLogoutResponseSuccess)

export const getAuthControllerLogoutUrl = () => {


  

  return `/auth/logout`
}

export const authControllerLogout = async ( options?: RequestInit): Promise<authControllerLogoutResponse> => {
  
  return orvalFetcher<authControllerLogoutResponse>(getAuthControllerLogoutUrl(),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}


export type authControllerRequestPasswordResetResponse201 = {
  data: void
  status: 201
}
    
export type authControllerRequestPasswordResetResponseSuccess = (authControllerRequestPasswordResetResponse201) & {
  headers: Headers;
};
;

export type authControllerRequestPasswordResetResponse = (authControllerRequestPasswordResetResponseSuccess)

export const getAuthControllerRequestPasswordResetUrl = (params: AuthControllerRequestPasswordResetParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/auth/requestPasswordReset?${stringifiedParams}` : `/auth/requestPasswordReset`
}

export const authControllerRequestPasswordReset = async (params: AuthControllerRequestPasswordResetParams, options?: RequestInit): Promise<authControllerRequestPasswordResetResponse> => {
  
  return orvalFetcher<authControllerRequestPasswordResetResponse>(getAuthControllerRequestPasswordResetUrl(params),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}


export type authControllerResetPasswordResponse201 = {
  data: void
  status: 201
}
    
export type authControllerResetPasswordResponseSuccess = (authControllerResetPasswordResponse201) & {
  headers: Headers;
};
;

export type authControllerResetPasswordResponse = (authControllerResetPasswordResponseSuccess)

export const getAuthControllerResetPasswordUrl = () => {


  

  return `/auth/resetPassword`
}

export const authControllerResetPassword = async (resetPasswordDto: ResetPasswordDto, options?: RequestInit): Promise<authControllerResetPasswordResponse> => {
  
  return orvalFetcher<authControllerResetPasswordResponse>(getAuthControllerResetPasswordUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      resetPasswordDto,)
  }
);}


