/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0
 */
import type {
  CreateEventDto,
  UpdateEventDto
} from './api.gen.schemas';

import { orvalFetcher } from '../lib/orval-fetcher';


/**
 * @summary Utwórz wydarzenie
 */
export type eventsControllerCreateResponse201 = {
  data: void
  status: 201
}

export type eventsControllerCreateResponse400 = {
  data: void
  status: 400
}

export type eventsControllerCreateResponse401 = {
  data: void
  status: 401
}
    
export type eventsControllerCreateResponseSuccess = (eventsControllerCreateResponse201) & {
  headers: Headers;
};
export type eventsControllerCreateResponseError = (eventsControllerCreateResponse400 | eventsControllerCreateResponse401) & {
  headers: Headers;
};

export type eventsControllerCreateResponse = (eventsControllerCreateResponseSuccess | eventsControllerCreateResponseError)

export const getEventsControllerCreateUrl = () => {


  

  return `/events`
}

export const eventsControllerCreate = async (createEventDto: CreateEventDto, options?: RequestInit): Promise<eventsControllerCreateResponse> => {
  
  return orvalFetcher<eventsControllerCreateResponse>(getEventsControllerCreateUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createEventDto,)
  }
);}


/**
 * @summary Lista wydarzeń zalogowanego użytkownika
 */
export type eventsControllerListResponse200 = {
  data: void
  status: 200
}

export type eventsControllerListResponse401 = {
  data: void
  status: 401
}
    
export type eventsControllerListResponseSuccess = (eventsControllerListResponse200) & {
  headers: Headers;
};
export type eventsControllerListResponseError = (eventsControllerListResponse401) & {
  headers: Headers;
};

export type eventsControllerListResponse = (eventsControllerListResponseSuccess | eventsControllerListResponseError)

export const getEventsControllerListUrl = () => {


  

  return `/events`
}

export const eventsControllerList = async ( options?: RequestInit): Promise<eventsControllerListResponse> => {
  
  return orvalFetcher<eventsControllerListResponse>(getEventsControllerListUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * @summary Pobierz pojedyncze wydarzenie
 */
export type eventsControllerGetOneResponse200 = {
  data: void
  status: 200
}

export type eventsControllerGetOneResponse401 = {
  data: void
  status: 401
}

export type eventsControllerGetOneResponse404 = {
  data: void
  status: 404
}
    
export type eventsControllerGetOneResponseSuccess = (eventsControllerGetOneResponse200) & {
  headers: Headers;
};
export type eventsControllerGetOneResponseError = (eventsControllerGetOneResponse401 | eventsControllerGetOneResponse404) & {
  headers: Headers;
};

export type eventsControllerGetOneResponse = (eventsControllerGetOneResponseSuccess | eventsControllerGetOneResponseError)

export const getEventsControllerGetOneUrl = (id: string,) => {


  

  return `/events/${id}`
}

export const eventsControllerGetOne = async (id: string, options?: RequestInit): Promise<eventsControllerGetOneResponse> => {
  
  return orvalFetcher<eventsControllerGetOneResponse>(getEventsControllerGetOneUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * @summary Aktualizuj wydarzenie
 */
export type eventsControllerUpdateResponse200 = {
  data: void
  status: 200
}

export type eventsControllerUpdateResponse400 = {
  data: void
  status: 400
}

export type eventsControllerUpdateResponse401 = {
  data: void
  status: 401
}

export type eventsControllerUpdateResponse404 = {
  data: void
  status: 404
}
    
export type eventsControllerUpdateResponseSuccess = (eventsControllerUpdateResponse200) & {
  headers: Headers;
};
export type eventsControllerUpdateResponseError = (eventsControllerUpdateResponse400 | eventsControllerUpdateResponse401 | eventsControllerUpdateResponse404) & {
  headers: Headers;
};

export type eventsControllerUpdateResponse = (eventsControllerUpdateResponseSuccess | eventsControllerUpdateResponseError)

export const getEventsControllerUpdateUrl = (id: string,) => {


  

  return `/events/${id}`
}

export const eventsControllerUpdate = async (id: string,
    updateEventDto: UpdateEventDto, options?: RequestInit): Promise<eventsControllerUpdateResponse> => {
  
  return orvalFetcher<eventsControllerUpdateResponse>(getEventsControllerUpdateUrl(id),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateEventDto,)
  }
);}


/**
 * @summary Usuń wydarzenie
 */
export type eventsControllerRemoveResponse204 = {
  data: void
  status: 204
}

export type eventsControllerRemoveResponse401 = {
  data: void
  status: 401
}

export type eventsControllerRemoveResponse404 = {
  data: void
  status: 404
}
    
export type eventsControllerRemoveResponseSuccess = (eventsControllerRemoveResponse204) & {
  headers: Headers;
};
export type eventsControllerRemoveResponseError = (eventsControllerRemoveResponse401 | eventsControllerRemoveResponse404) & {
  headers: Headers;
};

export type eventsControllerRemoveResponse = (eventsControllerRemoveResponseSuccess | eventsControllerRemoveResponseError)

export const getEventsControllerRemoveUrl = (id: string,) => {


  

  return `/events/${id}`
}

export const eventsControllerRemove = async (id: string, options?: RequestInit): Promise<eventsControllerRemoveResponse> => {
  
  return orvalFetcher<eventsControllerRemoveResponse>(getEventsControllerRemoveUrl(id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}


