/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0
 */
import { orvalFetcher } from '../lib/orval-fetcher';


export type healthControllerCheckResponse200 = {
  data: void
  status: 200
}
    
export type healthControllerCheckResponseSuccess = (healthControllerCheckResponse200) & {
  headers: Headers;
};
;

export type healthControllerCheckResponse = (healthControllerCheckResponseSuccess)

export const getHealthControllerCheckUrl = () => {


  

  return `/health`
}

export const healthControllerCheck = async ( options?: RequestInit): Promise<healthControllerCheckResponse> => {
  
  return orvalFetcher<healthControllerCheckResponse>(getHealthControllerCheckUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


