/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0
 */
import type {
  BulkCreateInviteesDto,
  InviteesControllerUpdateStatusBody
} from './api.gen.schemas';

import { orvalFetcher } from '../lib/orval-fetcher';


/**
 * @summary Masowe dodanie uczestników do wydarzenia
 */
export type inviteesControllerBulkResponse201 = {
  data: void
  status: 201
}

export type inviteesControllerBulkResponse400 = {
  data: void
  status: 400
}

export type inviteesControllerBulkResponse401 = {
  data: void
  status: 401
}

export type inviteesControllerBulkResponse404 = {
  data: void
  status: 404
}
    
export type inviteesControllerBulkResponseSuccess = (inviteesControllerBulkResponse201) & {
  headers: Headers;
};
export type inviteesControllerBulkResponseError = (inviteesControllerBulkResponse400 | inviteesControllerBulkResponse401 | inviteesControllerBulkResponse404) & {
  headers: Headers;
};

export type inviteesControllerBulkResponse = (inviteesControllerBulkResponseSuccess | inviteesControllerBulkResponseError)

export const getInviteesControllerBulkUrl = (eventId: string,) => {


  

  return `/events/${eventId}/invitees/bulk`
}

export const inviteesControllerBulk = async (eventId: string,
    bulkCreateInviteesDto: BulkCreateInviteesDto, options?: RequestInit): Promise<inviteesControllerBulkResponse> => {
  
  return orvalFetcher<inviteesControllerBulkResponse>(getInviteesControllerBulkUrl(eventId),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      bulkCreateInviteesDto,)
  }
);}


/**
 * @summary Lista uczestników wydarzenia
 */
export type inviteesControllerListResponse200 = {
  data: void
  status: 200
}
    
export type inviteesControllerListResponseSuccess = (inviteesControllerListResponse200) & {
  headers: Headers;
};
;

export type inviteesControllerListResponse = (inviteesControllerListResponseSuccess)

export const getInviteesControllerListUrl = (eventId: string,) => {


  

  return `/events/${eventId}/invitees`
}

export const inviteesControllerList = async (eventId: string, options?: RequestInit): Promise<inviteesControllerListResponse> => {
  
  return orvalFetcher<inviteesControllerListResponse>(getInviteesControllerListUrl(eventId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * @summary Usunięcie uczestnika z wydarzenia
 */
export type inviteesControllerDeleteResponse200 = {
  data: void
  status: 200
}
    
export type inviteesControllerDeleteResponseSuccess = (inviteesControllerDeleteResponse200) & {
  headers: Headers;
};
;

export type inviteesControllerDeleteResponse = (inviteesControllerDeleteResponseSuccess)

export const getInviteesControllerDeleteUrl = (eventId: string,
    inviteeId: string,) => {


  

  return `/events/${eventId}/invitees/${inviteeId}`
}

export const inviteesControllerDelete = async (eventId: string,
    inviteeId: string, options?: RequestInit): Promise<inviteesControllerDeleteResponse> => {
  
  return orvalFetcher<inviteesControllerDeleteResponse>(getInviteesControllerDeleteUrl(eventId,inviteeId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}


/**
 * @summary Aktualizacja statusu RSVP uczestnika
 */
export type inviteesControllerUpdateStatusResponse200 = {
  data: void
  status: 200
}
    
export type inviteesControllerUpdateStatusResponseSuccess = (inviteesControllerUpdateStatusResponse200) & {
  headers: Headers;
};
;

export type inviteesControllerUpdateStatusResponse = (inviteesControllerUpdateStatusResponseSuccess)

export const getInviteesControllerUpdateStatusUrl = (eventId: string,
    inviteeId: string,) => {


  

  return `/events/${eventId}/invitees/${inviteeId}/status`
}

export const inviteesControllerUpdateStatus = async (eventId: string,
    inviteeId: string,
    inviteesControllerUpdateStatusBody: InviteesControllerUpdateStatusBody, options?: RequestInit): Promise<inviteesControllerUpdateStatusResponse> => {
  
  return orvalFetcher<inviteesControllerUpdateStatusResponse>(getInviteesControllerUpdateStatusUrl(eventId,inviteeId),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      inviteesControllerUpdateStatusBody,)
  }
);}


/**
 * @summary Statystyki RSVP dla wydarzenia
 */
export type inviteesControllerStatsResponse200 = {
  data: void
  status: 200
}
    
export type inviteesControllerStatsResponseSuccess = (inviteesControllerStatsResponse200) & {
  headers: Headers;
};
;

export type inviteesControllerStatsResponse = (inviteesControllerStatsResponseSuccess)

export const getInviteesControllerStatsUrl = (eventId: string,) => {


  

  return `/events/${eventId}/invitees/stats`
}

export const inviteesControllerStats = async (eventId: string, options?: RequestInit): Promise<inviteesControllerStatsResponse> => {
  
  return orvalFetcher<inviteesControllerStatsResponse>(getInviteesControllerStatsUrl(eventId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


