/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0
 */
import type {
  CreateForInviteeDto,
  InvitationsStatsDto
} from './api.gen.schemas';



/**
 * @summary Utwórz zaproszenie dla wskazanego uczestnika
 */
export type invitationsControllerCreateForInviteeResponse201 = {
  data: void
  status: 201
}

export type invitationsControllerCreateForInviteeResponse400 = {
  data: void
  status: 400
}

export type invitationsControllerCreateForInviteeResponse401 = {
  data: void
  status: 401
}

export type invitationsControllerCreateForInviteeResponse404 = {
  data: void
  status: 404
}
    
export type invitationsControllerCreateForInviteeResponseSuccess = (invitationsControllerCreateForInviteeResponse201) & {
  headers: Headers;
};
export type invitationsControllerCreateForInviteeResponseError = (invitationsControllerCreateForInviteeResponse400 | invitationsControllerCreateForInviteeResponse401 | invitationsControllerCreateForInviteeResponse404) & {
  headers: Headers;
};

export type invitationsControllerCreateForInviteeResponse = (invitationsControllerCreateForInviteeResponseSuccess | invitationsControllerCreateForInviteeResponseError)

export const getInvitationsControllerCreateForInviteeUrl = (eventId: string,
    inviteeId: string,) => {


  

  return `/events/${eventId}/invitations/${inviteeId}`
}

export const invitationsControllerCreateForInvitee = async (eventId: string,
    inviteeId: string,
    createForInviteeDto: CreateForInviteeDto, options?: RequestInit): Promise<invitationsControllerCreateForInviteeResponse> => {
  
  const res = await fetch(getInvitationsControllerCreateForInviteeUrl(eventId,inviteeId),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createForInviteeDto,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: invitationsControllerCreateForInviteeResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as invitationsControllerCreateForInviteeResponse
}


/**
 * @summary Statystyki zaproszeń dla wydarzenia
 */
export type invitationsControllerStatsResponse200 = {
  data: InvitationsStatsDto
  status: 200
}

export type invitationsControllerStatsResponse401 = {
  data: void
  status: 401
}

export type invitationsControllerStatsResponse404 = {
  data: void
  status: 404
}
    
export type invitationsControllerStatsResponseSuccess = (invitationsControllerStatsResponse200) & {
  headers: Headers;
};
export type invitationsControllerStatsResponseError = (invitationsControllerStatsResponse401 | invitationsControllerStatsResponse404) & {
  headers: Headers;
};

export type invitationsControllerStatsResponse = (invitationsControllerStatsResponseSuccess | invitationsControllerStatsResponseError)

export const getInvitationsControllerStatsUrl = (eventId: string,) => {


  

  return `/events/${eventId}/invitations/stats`
}

export const invitationsControllerStats = async (eventId: string, options?: RequestInit): Promise<invitationsControllerStatsResponse> => {
  
  const res = await fetch(getInvitationsControllerStatsUrl(eventId),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: invitationsControllerStatsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as invitationsControllerStatsResponse
}


/**
 * @summary Wyślij e-mail z zaproszeniem
 */
export type invitationsControllerSendEmailResponse200 = {
  data: void
  status: 200
}

export type invitationsControllerSendEmailResponse401 = {
  data: void
  status: 401
}

export type invitationsControllerSendEmailResponse404 = {
  data: void
  status: 404
}
    
export type invitationsControllerSendEmailResponseSuccess = (invitationsControllerSendEmailResponse200) & {
  headers: Headers;
};
export type invitationsControllerSendEmailResponseError = (invitationsControllerSendEmailResponse401 | invitationsControllerSendEmailResponse404) & {
  headers: Headers;
};

export type invitationsControllerSendEmailResponse = (invitationsControllerSendEmailResponseSuccess | invitationsControllerSendEmailResponseError)

export const getInvitationsControllerSendEmailUrl = (eventId: string,
    invitationId: string,) => {


  

  return `/events/${eventId}/invitations/${invitationId}/send-email`
}

export const invitationsControllerSendEmail = async (eventId: string,
    invitationId: string, options?: RequestInit): Promise<invitationsControllerSendEmailResponse> => {
  
  const res = await fetch(getInvitationsControllerSendEmailUrl(eventId,invitationId),
  {      
    ...options,
    method: 'POST'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: invitationsControllerSendEmailResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as invitationsControllerSendEmailResponse
}


