/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0
 */
import type {
  BulkCreateInviteesDto
} from './api.gen.schemas';

import { orvalFetcher } from '../lib/orval-fetcher';


/**
 * @summary Masowe dodanie uczestników do wydarzenia
 */
export type inviteesControllerBulkResponse201 = {
  data: void
  status: 201
}

export type inviteesControllerBulkResponse400 = {
  data: void
  status: 400
}

export type inviteesControllerBulkResponse401 = {
  data: void
  status: 401
}

export type inviteesControllerBulkResponse404 = {
  data: void
  status: 404
}
    
export type inviteesControllerBulkResponseSuccess = (inviteesControllerBulkResponse201) & {
  headers: Headers;
};
export type inviteesControllerBulkResponseError = (inviteesControllerBulkResponse400 | inviteesControllerBulkResponse401 | inviteesControllerBulkResponse404) & {
  headers: Headers;
};

export type inviteesControllerBulkResponse = (inviteesControllerBulkResponseSuccess | inviteesControllerBulkResponseError)

export const getInviteesControllerBulkUrl = (eventId: string,) => {


  

  return `/events/${eventId}/invitees/bulk`
}

export const inviteesControllerBulk = async (eventId: string,
    bulkCreateInviteesDto: BulkCreateInviteesDto, options?: RequestInit): Promise<inviteesControllerBulkResponse> => {
  
  return orvalFetcher<inviteesControllerBulkResponse>(getInviteesControllerBulkUrl(eventId),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      bulkCreateInviteesDto,)
  }
);}


/**
 * @summary Lista uczestników wydarzenia
 */
export type inviteesControllerListResponse200 = {
  data: void
  status: 200
}

export type inviteesControllerListResponse401 = {
  data: void
  status: 401
}

export type inviteesControllerListResponse404 = {
  data: void
  status: 404
}
    
export type inviteesControllerListResponseSuccess = (inviteesControllerListResponse200) & {
  headers: Headers;
};
export type inviteesControllerListResponseError = (inviteesControllerListResponse401 | inviteesControllerListResponse404) & {
  headers: Headers;
};

export type inviteesControllerListResponse = (inviteesControllerListResponseSuccess | inviteesControllerListResponseError)

export const getInviteesControllerListUrl = (eventId: string,) => {


  

  return `/events/${eventId}/invitees`
}

export const inviteesControllerList = async (eventId: string, options?: RequestInit): Promise<inviteesControllerListResponse> => {
  
  return orvalFetcher<inviteesControllerListResponse>(getInviteesControllerListUrl(eventId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


