/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0
 */
import type {
  CreateProgramItemDto,
  ProgramControllerBulkBody,
  ProgramControllerList200Item,
  ProgramControllerReorderBody,
  UpdateProgramItemDto
} from './api.gen.schemas';

import { orvalFetcher } from '../lib/orval-fetcher';


/**
 * @summary Lista punktów programu
 */
export type programControllerListResponse200 = {
  data: ProgramControllerList200Item[]
  status: 200
}

export type programControllerListResponse401 = {
  data: void
  status: 401
}
    
export type programControllerListResponseSuccess = (programControllerListResponse200) & {
  headers: Headers;
};
export type programControllerListResponseError = (programControllerListResponse401) & {
  headers: Headers;
};

export type programControllerListResponse = (programControllerListResponseSuccess | programControllerListResponseError)

export const getProgramControllerListUrl = (eventId: string,) => {


  

  return `/events/${eventId}/program`
}

export const programControllerList = async (eventId: string, options?: RequestInit): Promise<programControllerListResponse> => {
  
  return orvalFetcher<programControllerListResponse>(getProgramControllerListUrl(eventId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * @summary Dodaj punkt programu
 */
export type programControllerCreateResponse201 = {
  data: void
  status: 201
}

export type programControllerCreateResponse400 = {
  data: void
  status: 400
}
    
export type programControllerCreateResponseSuccess = (programControllerCreateResponse201) & {
  headers: Headers;
};
export type programControllerCreateResponseError = (programControllerCreateResponse400) & {
  headers: Headers;
};

export type programControllerCreateResponse = (programControllerCreateResponseSuccess | programControllerCreateResponseError)

export const getProgramControllerCreateUrl = (eventId: string,) => {


  

  return `/events/${eventId}/program`
}

export const programControllerCreate = async (eventId: string,
    createProgramItemDto: CreateProgramItemDto, options?: RequestInit): Promise<programControllerCreateResponse> => {
  
  return orvalFetcher<programControllerCreateResponse>(getProgramControllerCreateUrl(eventId),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createProgramItemDto,)
  }
);}


/**
 * @summary Aktualizuj punkt programu
 */
export type programControllerUpdateResponse200 = {
  data: void
  status: 200
}

export type programControllerUpdateResponse404 = {
  data: void
  status: 404
}
    
export type programControllerUpdateResponseSuccess = (programControllerUpdateResponse200) & {
  headers: Headers;
};
export type programControllerUpdateResponseError = (programControllerUpdateResponse404) & {
  headers: Headers;
};

export type programControllerUpdateResponse = (programControllerUpdateResponseSuccess | programControllerUpdateResponseError)

export const getProgramControllerUpdateUrl = (eventId: string,
    itemId: string,) => {


  

  return `/events/${eventId}/program/${itemId}`
}

export const programControllerUpdate = async (eventId: string,
    itemId: string,
    updateProgramItemDto: UpdateProgramItemDto, options?: RequestInit): Promise<programControllerUpdateResponse> => {
  
  return orvalFetcher<programControllerUpdateResponse>(getProgramControllerUpdateUrl(eventId,itemId),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateProgramItemDto,)
  }
);}


/**
 * @summary Usuń punkt programu
 */
export type programControllerRemoveResponse200 = {
  data: void
  status: 200
}

export type programControllerRemoveResponse404 = {
  data: void
  status: 404
}
    
export type programControllerRemoveResponseSuccess = (programControllerRemoveResponse200) & {
  headers: Headers;
};
export type programControllerRemoveResponseError = (programControllerRemoveResponse404) & {
  headers: Headers;
};

export type programControllerRemoveResponse = (programControllerRemoveResponseSuccess | programControllerRemoveResponseError)

export const getProgramControllerRemoveUrl = (eventId: string,
    itemId: string,) => {


  

  return `/events/${eventId}/program/${itemId}`
}

export const programControllerRemove = async (eventId: string,
    itemId: string, options?: RequestInit): Promise<programControllerRemoveResponse> => {
  
  return orvalFetcher<programControllerRemoveResponse>(getProgramControllerRemoveUrl(eventId,itemId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}


/**
 * @summary Masowe dodanie punktów programu
 */
export type programControllerBulkResponse201 = {
  data: void
  status: 201
}
    
export type programControllerBulkResponseSuccess = (programControllerBulkResponse201) & {
  headers: Headers;
};
;

export type programControllerBulkResponse = (programControllerBulkResponseSuccess)

export const getProgramControllerBulkUrl = (eventId: string,) => {


  

  return `/events/${eventId}/program/bulk`
}

export const programControllerBulk = async (eventId: string,
    programControllerBulkBody: ProgramControllerBulkBody, options?: RequestInit): Promise<programControllerBulkResponse> => {
  
  return orvalFetcher<programControllerBulkResponse>(getProgramControllerBulkUrl(eventId),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      programControllerBulkBody,)
  }
);}


/**
 * @summary Zmień kolejność punktów programu
 */
export type programControllerReorderResponse200 = {
  data: void
  status: 200
}
    
export type programControllerReorderResponseSuccess = (programControllerReorderResponse200) & {
  headers: Headers;
};
;

export type programControllerReorderResponse = (programControllerReorderResponseSuccess)

export const getProgramControllerReorderUrl = (eventId: string,) => {


  

  return `/events/${eventId}/program/reorder`
}

export const programControllerReorder = async (eventId: string,
    programControllerReorderBody: ProgramControllerReorderBody, options?: RequestInit): Promise<programControllerReorderResponse> => {
  
  return orvalFetcher<programControllerReorderResponse>(getProgramControllerReorderUrl(eventId),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      programControllerReorderBody,)
  }
);}


