/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0
 */
import type {
  PublicInvitationGetResponseDto,
  PublicRsvpDto,
  PublicRsvpResponseDto
} from './api.gen.schemas';

import { orvalFetcher } from '../lib/orval-fetcher';


/**
 * @summary Pobierz publiczne zaproszenie po kodzie
 */
export type publicInvitationsControllerGetResponse200 = {
  data: PublicInvitationGetResponseDto
  status: 200
}

export type publicInvitationsControllerGetResponse404 = {
  data: void
  status: 404
}
    
export type publicInvitationsControllerGetResponseSuccess = (publicInvitationsControllerGetResponse200) & {
  headers: Headers;
};
export type publicInvitationsControllerGetResponseError = (publicInvitationsControllerGetResponse404) & {
  headers: Headers;
};

export type publicInvitationsControllerGetResponse = (publicInvitationsControllerGetResponseSuccess | publicInvitationsControllerGetResponseError)

export const getPublicInvitationsControllerGetUrl = (code: string,) => {


  

  return `/p/${code}`
}

export const publicInvitationsControllerGet = async (code: string, options?: RequestInit): Promise<publicInvitationsControllerGetResponse> => {
  
  return orvalFetcher<publicInvitationsControllerGetResponse>(getPublicInvitationsControllerGetUrl(code),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * @summary Złóż publiczne RSVP dla zaproszenia
 */
export type publicInvitationsControllerRsvpResponse200 = {
  data: PublicRsvpResponseDto
  status: 200
}

export type publicInvitationsControllerRsvpResponse404 = {
  data: void
  status: 404
}
    
export type publicInvitationsControllerRsvpResponseSuccess = (publicInvitationsControllerRsvpResponse200) & {
  headers: Headers;
};
export type publicInvitationsControllerRsvpResponseError = (publicInvitationsControllerRsvpResponse404) & {
  headers: Headers;
};

export type publicInvitationsControllerRsvpResponse = (publicInvitationsControllerRsvpResponseSuccess | publicInvitationsControllerRsvpResponseError)

export const getPublicInvitationsControllerRsvpUrl = (code: string,) => {


  

  return `/p/${code}/rsvp`
}

export const publicInvitationsControllerRsvp = async (code: string,
    publicRsvpDto: PublicRsvpDto, options?: RequestInit): Promise<publicInvitationsControllerRsvpResponse> => {
  
  return orvalFetcher<publicInvitationsControllerRsvpResponse>(getPublicInvitationsControllerRsvpUrl(code),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      publicRsvpDto,)
  }
);}


