/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0
 */
import type {
  PublicInvitationGetResponseDto,
  PublicRsvpDto,
  PublicRsvpResponseDto
} from './api.gen.schemas';



/**
 * @summary Pobierz publiczne zaproszenie po kodzie
 */
export type publicInvitationsControllerGetResponse200 = {
  data: PublicInvitationGetResponseDto
  status: 200
}

export type publicInvitationsControllerGetResponse404 = {
  data: void
  status: 404
}
    
export type publicInvitationsControllerGetResponseSuccess = (publicInvitationsControllerGetResponse200) & {
  headers: Headers;
};
export type publicInvitationsControllerGetResponseError = (publicInvitationsControllerGetResponse404) & {
  headers: Headers;
};

export type publicInvitationsControllerGetResponse = (publicInvitationsControllerGetResponseSuccess | publicInvitationsControllerGetResponseError)

export const getPublicInvitationsControllerGetUrl = (code: string,) => {


  

  return `/p/${code}`
}

export const publicInvitationsControllerGet = async (code: string, options?: RequestInit): Promise<publicInvitationsControllerGetResponse> => {
  
  const res = await fetch(getPublicInvitationsControllerGetUrl(code),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: publicInvitationsControllerGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as publicInvitationsControllerGetResponse
}


/**
 * @summary Złóż publiczne RSVP dla zaproszenia
 */
export type publicInvitationsControllerRsvpResponse200 = {
  data: PublicRsvpResponseDto
  status: 200
}

export type publicInvitationsControllerRsvpResponse404 = {
  data: void
  status: 404
}
    
export type publicInvitationsControllerRsvpResponseSuccess = (publicInvitationsControllerRsvpResponse200) & {
  headers: Headers;
};
export type publicInvitationsControllerRsvpResponseError = (publicInvitationsControllerRsvpResponse404) & {
  headers: Headers;
};

export type publicInvitationsControllerRsvpResponse = (publicInvitationsControllerRsvpResponseSuccess | publicInvitationsControllerRsvpResponseError)

export const getPublicInvitationsControllerRsvpUrl = (code: string,) => {


  

  return `/p/${code}/rsvp`
}

export const publicInvitationsControllerRsvp = async (code: string,
    publicRsvpDto: PublicRsvpDto, options?: RequestInit): Promise<publicInvitationsControllerRsvpResponse> => {
  
  const res = await fetch(getPublicInvitationsControllerRsvpUrl(code),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      publicRsvpDto,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: publicInvitationsControllerRsvpResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as publicInvitationsControllerRsvpResponse
}


