/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0
 */
import { orvalFetcher } from '../lib/orval-fetcher';


export type usersControllerGetMeResponse200 = {
  data: void
  status: 200
}
    
export type usersControllerGetMeResponseSuccess = (usersControllerGetMeResponse200) & {
  headers: Headers;
};
;

export type usersControllerGetMeResponse = (usersControllerGetMeResponseSuccess)

export const getUsersControllerGetMeUrl = () => {


  

  return `/users/me`
}

export const usersControllerGetMe = async ( options?: RequestInit): Promise<usersControllerGetMeResponse> => {
  
  return orvalFetcher<usersControllerGetMeResponse>(getUsersControllerGetMeUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


