/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0
 */


export type usersControllerGetMeResponse200 = {
  data: void
  status: 200
}
    
export type usersControllerGetMeResponseSuccess = (usersControllerGetMeResponse200) & {
  headers: Headers;
};
;

export type usersControllerGetMeResponse = (usersControllerGetMeResponseSuccess)

export const getUsersControllerGetMeUrl = () => {


  

  return `/users/me`
}

export const usersControllerGetMe = async ( options?: RequestInit): Promise<usersControllerGetMeResponse> => {
  
  const res = await fetch(getUsersControllerGetMeUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: usersControllerGetMeResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as usersControllerGetMeResponse
}


